### PR TITLE
Replaced Guid with uguid

### PR DESCRIPTION
**Pull request by morr0ne**

### CODE REVIEW

**Comment by dvdhrm** [comment]
Hi! Thanks for the submission!

Can you add a rationale to the commit and explain why you are doing this? Currently, neither the PR nor the commit-message contain any explanation.

**Comment by morr0ne** [comment]
Hi, extremely sorry about this. I thought I had written an explanation but either me or github actually forgot to include it.

I replaced the custom Guid type with one of the crates provided by https://github.com/google/gpt-disk-rs. There are multiple reasons for this change:

- Better integration with the rest of the ecosystem
- More convenience features like the guid macro
- A much more robust implementation that gets frequently updated and is properly tested in a gpt ecosystem
- A slightly different internal layout that is more inline with the actual spec

This also removes the maintainment burden from this crate which imo should only worry about the uefi side of things.
The uguid crate also seems to be pretty much the standard when dealing with gpt and it's being used in google products despite not being officially endorsed by them

There are only benefits to switching the only downside being having to release a new major version

**Comment by dvdhrm** [comment]
> Hi, extremely sorry about this. I thought I had written an explanation but either me or github actually forgot to include it.

No worries!

> I replaced the custom Guid type with one of the crates provided by https://github.com/google/gpt-disk-rs. There are multiple reasons for this change:
> 
>     * Better integration with the rest of the ecosystem

Just for the record, you can transmute between `r_efi::Guid` and `uguid::Guid` safely, since both guarantee the same memory layout and runtime restrictions. I mean, that's literally the purpose of those types, so this is safe.

>     * More convenience features like the guid macro

Convenience features are explicitly out of scope of `r-efi`. We explicitly want dependent crates to add them.

>     * A much more robust implementation that gets frequently updated and is properly tested in a gpt ecosystem

In what way is the `r-efi` implementation less robust?

>     * A slightly different internal layout that is more inline with the actual spec

Can you elaborate? The layout is identical, to my knowledge, with the only exception that `uguid` uses a `u32` to enforce alignment, while `r-efi` uses `repr(align(4))`.

What do you mean `more inline with the actual spec`? In what way is `r-efi` not perfectly inline with the UEFI spec?

> This also removes the maintainment burden from this crate which imo should only worry about the uefi side of things.

I think both GPT and GUID are part of UEFI, rather than a separate effort. GPT is literally defined by the some body, and GUID is primarily used by UEFI outside of the Windows world, so UEFI is a suitable place to define it, in my opinion. So I am fine keeping it as part of `r-efi`, given that it is defined in the UEFI specification.

> There are only benefits to switching the only downside being having to release a new major version

The purpose of `r-efi` is to provide all raw definitions from the specification with as little manual intervention as possible. The idea is to allow access to UEFI definitions by only looking at the UEFI specification, and not requiring any knowledge of how each individual part is transposed to Rust.

On top, we do not want to provide any convenience helpers, since this would undoubtedly lead to policy discussions. This is all out of scope of `r-efi` and explicitly deferred to dependent packages. `r-efi` merely ensures that implementation of such helpers is possible and safe.

While I do not doubt the advantages of helper types, this is not inline with the policy behind `r-efi`. It would add a dependency to a crate that has none so far. It would require users to audit an additional dependency (possibly transitively), if they have that as part of their company policy. `r-efi` would no longer be a tail in the dependency tree.

Note that your approach is certainly valid, and packages like `uefi-rs` take that route. However, I think this is not a suitable match for `r-efi`.

**Comment by dvdhrm** [comment]
I will close this due to inactivity. Feel free to reopen if you want to continue the discussion!

Thanks for the report!

**Pull request closed without merging**
